### ISSUE TITLE
options for sha1 digest encoding

### ISSUE THREAD

**Issue by sabrinaluo** [bouzuya/node-wsse#1]
can you add options for `sha1` digest encoding?
if no argument, use `base64` by defaulf.
if there is any, use the option argument.

Thank you :)

**Comment by bouzuya** [comment]
Why do you need the option?

`Password_Digest = Base64 ( SHA-1 ( nonce + created + password ) )`

http://www.xml.com/pub/a/2003/12/17/dive.html

**Comment by sabrinaluo** [comment]
Thanks for your reply :)

to make it as an x-wsse header, need to return `this._base64(sha1.digest('hex'))` instead of `sha1.digest('base64')` (this can not work with emarsys, because the `passwordDigest` can't pass its authentication, I don't know why)

I want to integrate nodejs with emarsys API, they don't provide js sample code, hope sample in ruby can help.
http://documentation.emarsys.com/resource/developers/api/getting-started/authentication/
http://documentation.emarsys.com/resource/developers/api/getting-started/authentication/ruby-sample/

**Comment by bouzuya** [comment]
This sample code is wrong. Emarsys's WSSE implmentation is broken.
http://documentation.emarsys.com/resource/developers/api/getting-started/authentication/ruby-sample/

`Base64(SHA1 ("d36e316282959a9ed4c89851497a717f" + "2003-12-15T14:43:07Z" + "taadtaadpstcsm"))` is `"quR/EWLAV4xLf9Zqyw4pDmfV90Y="`

**Comment by bouzuya** [comment]
Other examples.

`symfony-wsse` 
https://github.com/alcalyn/symfony-wsse/blob/master/Security/Authentication/Provider/PasswordDigestValidator.php#L61

> $expected = base64_encode(sha1(base64_decode($nonce).$created.$secret, true)); // sha1 returns raw

Emarsys's sample
http://documentation.emarsys.com/resource/developers/api/getting-started/authentication/php-sample/

> $passwordDigest = base64_encode(sha1($nonce . $timestamp . $this->_secret, false)); // sha1 returns hex

**Comment by sabrinaluo** [comment]
Sorry that I did't do enough research about WSSE before submiting the issue.  Thanks for working so late to reply me, wish you have a good night. oyasumi :)

After searching some documentation, I'm getting confused, seems both of them are correct?

http://documentation.emarsys.com/resource/developers/api/getting-started/authentication/
Section: Computing the Password Digest, step 4

> Calculate the SHA1 hash value of the concatenated string, and **make sure this value is in hexadecimal** format!

https://marketing.adobe.com/developer/cn/documentation/authentication-1/wsse-authentication-2
Section: The process looks like this, step 3

> Generate a digest hash string using the sha1 one-way hashing algorithm. The input the the sha1 hash is simply a concatenation of the nonce, created timestamp, and the API secret. Please note that the sha1 output should be binary, **not hexadecimal**. 

https://books.google.com.hk/books?id=wIWU94zKEtYC&pg=PT315&lpg=PT315&dq=wsse+sha1+hex&source=bl&ots=PqxRR5Bby3&sig=5vgDuuc97LoeQSv3d37bx9FOuC8&hl=zh-CN&sa=X&ved=0ahUKEwiP57Dz0czJAhVFHZQKHXZmCvU4ChDoAQghMAE#v=onepage&q=wsse%20sha1%20hex&f=false
(not sure whether you can open above link or not, you can find the book here also http://book.soundonair.ru/web/web2apps-CHP-11-SECT-1.html  in section 11.1.8)
BOOK: Building Scalable Web Sites: Building, Scaling, and Optimizing the Next Generation of Web Applications
ISBN: 0596555245, 9780596555245
PAGE: 299

> There are some problems with WSSE in practice. First, the specification was cloudy as to whether a binary or ASCII hexadecimal representation of the SHA1 sum was to be used, although the binary version seems to be the intention, hence the need for the base64 encoding to make the digest 7-bit safe. Different vendors have implemented their support using each of the two alternatives, creating mutually exclusive systems.

**Comment by bouzuya** [comment]
OK. I will try to consider it.

**Comment by bouzuya** [comment]
I added `sha1encoding` option to UsernameToken constructor in v2.3.0.

**Comment by sabrinaluo** [comment]
Thanks XD

**Comment by bouzuya** [comment]
:+1:
